name: Build
on:
  push:
    branches:
      - master
    paths:
      - lib/**
      - android/**
      - linux/**
      - pubspec.yaml
      - pubspec.lock

jobs:
  # Android build
  android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      STORE_FILE: "/tmp/keystore.jks"
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true
        cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
        cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
        pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:"
    - name: Build KeyStore
      run: echo ${{ secrets.STORE_BASE64 }} | base64 -d > ${{ env.STORE_FILE }}
    - name: Write key.properties
      run: |
        echo "storePassword=${{ secrets.STORE_PASSWORD }}" > android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
        echo "storeFile=${{ env.STORE_FILE }}" >> android/key.properties
    - name: Get Flutter pubs
      run: flutter pub get
    - name: Build Android
      run: flutter build apk --split-per-abi --target-platform android-arm64,android-arm --split-debug-info build/app/outputs/symbols
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-artifact
        path: ./build/app/outputs/flutter-apk/app-*-release.apk
  # Linux build
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Linux build deps
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: ninja-build libgtk-3-dev libmpv-dev
        version: 1.0
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true
        cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
        cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
        pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:"
    - name: Get Flutter pubs
      run: flutter pub get
    - name: Build Linux
      run: flutter build linux --split-debug-info build/app/outputs/symbols
    - name: Zip Linux build
      run: zip -qq -r linux-x64.zip *
      working-directory: ./build/linux/x64/release/bundle
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-artifact
        path: ./build/linux/x64/release/bundle/linux-x64.zip
  # Windows build
  windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true
        cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
        cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
        pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:"
    - name: Get Flutter pubs
      run: flutter pub get
    - name: Build Windows
      run: flutter build windows --split-debug-info build\app\outputs\symbols
    - name: Zip windows dir
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        directory: .\build\windows\x64\runner\Release
        filename: 'windows-x64.zip'
      working-directory: .\build\windows\x64\runner\Release
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-artifact
        path: .\build\windows\x64\runner\Release\windows-x64.zip
